// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: divide.proto

package com.gojek.test.divide;

public interface NumbersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:divide.Numbers)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 a = 1;</code>
   */
  int getA();

  /**
   * <code>int32 b = 2;</code>
   */
  int getB();
}
