// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: divide.proto

package com.gojek.test.divide;

public interface RespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:divide.Resp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 q = 1;</code>
   */
  int getQ();
}
